# Generated by Django 5.2.6 on 2025-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя в Telegram')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('passenger', 'Пассажир'), ('driver', 'Водитель')], default='passenger', max_length=10, verbose_name='Роль')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский'), ('tj', 'Таджикский')], default='ru', max_length=2, verbose_name='Язык интерфейса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
