# Generated by Django 5.2.6 on 2025-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Не проверен'), ('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='not_verified', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('passenger', 'Пассажир'), ('driver', 'Водитель')], max_length=10, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID пользователя в Телеграм'),
        ),
    ]
