# Generated by Django 5.2.6 on 2025-09-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'Обращение в поддержку', 'verbose_name_plural': 'Обращения в поддержку'},
        ),
    ]
