# Generated by Django 5.2.6 on 2025-09-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_location',
            field=models.CharField(max_length=100, verbose_name='Место отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_location',
            field=models.CharField(max_length=100, verbose_name='Место назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to='users.user', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за место'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.user', verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveSmallIntegerField(verbose_name='Забронировано мест')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_passenger', to='users.user', verbose_name='Пассажир')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'unique_together': {('trip', 'passenger')},
            },
        ),
    ]
